import Foundation

@available(macOS 12.0, iOS 15.0, *)
extension DataBase {
    static let french_list: [Phoneme] = [
        Phoneme(symbol: "i", ipaNotation: "i", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "e", ipaNotation: "e", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ɛ", ipaNotation: "ɛ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "a", ipaNotation: "a", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ɑ", ipaNotation: "ɑ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "o", ipaNotation: "o", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ɔ", ipaNotation: "ɔ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "u", ipaNotation: "u", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "y", ipaNotation: "y", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ø", ipaNotation: "ø", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "œ", ipaNotation: "œ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "w", ipaNotation: "w", type: .semivowel, x: 0, y: 0),
        Phoneme(symbol: "ɥ", ipaNotation: "ɥ", type: .semivowel, x: 0, y: 0),
        Phoneme(symbol: "j", ipaNotation: "j", type: .semivowel, x: 0, y: 0),
        Phoneme(symbol: "p", ipaNotation: "p", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "b", ipaNotation: "b", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "t", ipaNotation: "t", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "d", ipaNotation: "d", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "k", ipaNotation: "k", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "g", ipaNotation: "g", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "f", ipaNotation: "f", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "v", ipaNotation: "v", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "s", ipaNotation: "s", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "z", ipaNotation: "z", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ʃ", ipaNotation: "ʃ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ʒ", ipaNotation: "ʒ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "m", ipaNotation: "m", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "n", ipaNotation: "n", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ɲ", ipaNotation: "ɲ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ŋ", ipaNotation: "ŋ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "l", ipaNotation: "l", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ʁ", ipaNotation: "ʁ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ɑ̃", ipaNotation: "ɑ̃", type: .nasal, x: 0, y: 0),
        Phoneme(symbol: "ɛ̃", ipaNotation: "ɛ̃", type: .nasal, x: 0, y: 0),
        Phoneme(symbol: "œ̃", ipaNotation: "œ̃", type: .nasal, x: 0, y: 0),
        Phoneme(symbol: "ɔ̃", ipaNotation: "ɔ̃", type: .nasal, x: 0, y: 0),
        Phoneme(symbol: ",", ipaNotation: ",", type: .stress, x: 0, y: 0),
        Phoneme(symbol: "ˈ", ipaNotation: "ˈ", type: .stress, x: 0, y: 0),
        Phoneme(symbol: "‖", ipaNotation: "‖", type: .pause, x: 0, y: 0),
        Phoneme(symbol: "‖‖", ipaNotation: "‖‖", type: .pause,  x: 0, y: 0)]
}
