import Foundation

@available(macOS 12.0, iOS 15.0, *)
extension DataBase {
    //MARK: - English GB
    static let english_GB_list: [Phoneme] = [
        Phoneme(symbol: "iː", ipaNotation: "iː", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ɪ", ipaNotation: "ɪ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "e", ipaNotation: "e", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "æ", ipaNotation: "æ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "aː", ipaNotation: "aː", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ɒ", ipaNotation: "ɒ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ɔː", ipaNotation: "ɔː", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ʊ", ipaNotation: "ʊ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "uː", ipaNotation: "uː", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ɜː", ipaNotation: "ɜː", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ə", ipaNotation: "ə", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "eɪ", ipaNotation: "eɪ", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "aɪ", ipaNotation: "aɪ", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "ɔɪ", ipaNotation: "ɔɪ", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "aʊ", ipaNotation: "aʊ", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "oʊ", ipaNotation: "oʊ", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "ɪə", ipaNotation: "ɪə", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "eə", ipaNotation: "eə", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "ʊə", ipaNotation: "ʊə", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "p", ipaNotation: "p", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "b", ipaNotation: "b", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "t", ipaNotation: "t", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "d", ipaNotation: "d", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "k", ipaNotation: "k", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "g", ipaNotation: "g", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ʧ", ipaNotation: "ʧ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ʤ", ipaNotation: "ʤ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "f", ipaNotation: "f", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "v", ipaNotation: "v", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "θ", ipaNotation: "θ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ð", ipaNotation: "ð", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "s", ipaNotation: "s", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "z", ipaNotation: "z", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ʃ", ipaNotation: "ʃ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ʒ", ipaNotation: "ʒ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "h", ipaNotation: "h", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "m", ipaNotation: "m", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "n", ipaNotation: "n", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ŋ", ipaNotation: "ŋ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "l", ipaNotation: "l", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "r", ipaNotation: "r", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "j", ipaNotation: "j", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "w", ipaNotation: "w", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: ",", ipaNotation: ",", type: .stress, x: 0, y: 0),
        Phoneme(symbol: "ˈ", ipaNotation: "ˈ", type: .stress, x: 0, y: 0),
        Phoneme(symbol: "‖", ipaNotation: "‖", type: .pause, x: 0, y: 0),
        Phoneme(symbol: "‖‖", ipaNotation: "‖‖", type: .pause,  x: 0, y: 0)
    ]
    
    //MARK: - English US
    static let english_US_list: [Phoneme] = [
        Phoneme(symbol: "i", ipaNotation: "i", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ɪ", ipaNotation: "ɪ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "e", ipaNotation: "e", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ɛ", ipaNotation: "ɛ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "æ", ipaNotation: "æ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "u", ipaNotation: "u", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ʊ", ipaNotation: "ʊ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "o", ipaNotation: "o", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ɔ", ipaNotation: "ɔ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ɑ", ipaNotation: "ɑ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ʌ", ipaNotation: "ʌ", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "ə", ipaNotation: "ə", type: .vowel, x: 0, y: 0),
        Phoneme(symbol: "aɪ", ipaNotation: "aɪ", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "aʊ", ipaNotation: "aʊ", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "ɔɪ", ipaNotation: "ɔɪ", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "oʊ", ipaNotation: "oʊ", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "eɪ", ipaNotation: "eɪ", type: .diphthong, x: 0, y: 0),
        Phoneme(symbol: "p", ipaNotation: "p", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "b", ipaNotation: "b", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "t", ipaNotation: "t", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "d", ipaNotation: "d", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "k", ipaNotation: "k", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "g", ipaNotation: "g", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "f", ipaNotation: "f", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "v", ipaNotation: "v", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "θ", ipaNotation: "θ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ð", ipaNotation: "ð", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "s", ipaNotation: "s", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "z", ipaNotation: "z", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ʃ", ipaNotation: "ʃ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ʒ", ipaNotation: "ʒ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "tʃ", ipaNotation: "tʃ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "dʒ", ipaNotation: "dʒ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "m", ipaNotation: "m", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "n", ipaNotation: "n", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "ŋ", ipaNotation: "ŋ", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "l", ipaNotation: "l", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "r", ipaNotation: "r", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: "w", ipaNotation: "w", type: .semivowel, x: 0, y: 0),
        Phoneme(symbol: "j", ipaNotation: "j", type: .semivowel, x: 0, y: 0),
        Phoneme(symbol: "h", ipaNotation: "h", type: .consonant, x: 0, y: 0),
        Phoneme(symbol: ",", ipaNotation: ",", type: .stress, x: 0, y: 0),
        Phoneme(symbol: "ˈ", ipaNotation: "ˈ", type: .stress, x: 0, y: 0),
        Phoneme(symbol: "‖", ipaNotation: "‖", type: .pause, x: 0, y: 0),
        Phoneme(symbol: "‖‖", ipaNotation: "‖‖", type: .pause,  x: 0, y: 0)]
}
